#!/bin/sh
#
# Build a native Linux package of trace from the source tree in the current
# directory:
#
#   packaging/build-package.sh deb    Debian/Ubuntu  → dist/trace_<ver>-1_<arch>.deb
#   packaging/build-package.sh rpm    Fedora/RHEL    → dist/trace-<ver>-1.<arch>.rpm
#   packaging/build-package.sh arch   Arch Linux     → dist/trace-<ver>-1-<arch>.pkg.tar.zst
#
# Meant to run inside a container of the target distribution (the release
# workflow uses debian:bookworm, fedora:latest and archlinux:base-devel), so
# the binary links against that distribution's libraries. When run as root it
# installs the build dependencies it needs; Rust comes from rustup when no
# `cargo` is available (Arch uses the distribution's rust package instead).
set -eu

KIND="${1:-}"
case "$KIND" in
    deb | rpm | arch) ;;
    *)
        echo "usage: $0 deb|rpm|arch" >&2
        exit 2
        ;;
esac

[ -f Cargo.toml ] || { echo "run from the trace source root" >&2; exit 2; }
VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n 1)"
DIST="$(pwd)/dist"
mkdir -p "$DIST"

is_root() { [ "$(id -u)" = "0" ]; }

install_deps() {
    is_root || return 0
    case "$KIND" in
        deb)
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -qq
            apt-get install -y -qq --no-install-recommends \
                build-essential ca-certificates curl git gzip pkg-config dpkg-dev >/dev/null
            ;;
        rpm)
            dnf install -y -q gcc gcc-c++ make curl git gzip findutils >/dev/null
            ;;
        arch)
            pacman -Syu --noconfirm --needed base-devel git rust >/dev/null
            ;;
    esac
}

ensure_rust() {
    if ! command -v cargo >/dev/null 2>&1; then
        if [ -x "${HOME}/.cargo/bin/cargo" ]; then
            PATH="${HOME}/.cargo/bin:${PATH}"
        else
            curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --no-modify-path
            PATH="${HOME}/.cargo/bin:${PATH}"
        fi
        export PATH
    fi
    cargo --version
}

# Shell completions and the man page, generated by the built binary.
gen_assets() {
    bin="$1"
    out="target/assets"
    mkdir -p "$out/completions"
    "$bin" completions bash > "$out/completions/trace.bash"
    "$bin" completions zsh > "$out/completions/_trace"
    "$bin" completions fish > "$out/completions/trace.fish"
    "$bin" man > "$out/trace.1"
    gzip -9nf "$out/trace.1"
}

build_deb() {
    ensure_rust
    command -v cargo-deb >/dev/null 2>&1 || cargo install cargo-deb --locked
    cargo build --release --locked
    gen_assets target/release/trace
    cargo deb --no-build --no-strip
    cp target/debian/trace_"${VERSION}"-1_*.deb "$DIST/"
}

build_rpm() {
    ensure_rust
    command -v cargo-generate-rpm >/dev/null 2>&1 || cargo install cargo-generate-rpm --locked
    cargo build --release --locked
    gen_assets target/release/trace
    cargo generate-rpm
    cp target/generate-rpm/trace-"${VERSION}"-1.*.rpm "$DIST/"
}

# makepkg refuses to run as root: build as an unprivileged user from a
# tarball of this tree, exactly as an AUR user would from the release tag.
build_arch() {
    work="$(mktemp -d)"
    cp packaging/arch/PKGBUILD "$work/"
    sed -i "s/^pkgver=.*/pkgver=${VERSION}/" "$work/PKGBUILD"
    # The source here is a tarball of this tree, not the release tag, so its
    # checksum cannot match whatever the PKGBUILD pins (and computing one
    # would need pacman-contrib for updpkgsums).
    sed -i "s/^sha256sums=.*/sha256sums=('SKIP')/" "$work/PKGBUILD"
    tar --exclude=./target --exclude=./dist --exclude=./.git --exclude=./.trace \
        --transform "s,^\.,trace-${VERSION}," -czf "$work/trace-${VERSION}.tar.gz" .
    if is_root; then
        id builder >/dev/null 2>&1 || useradd -m builder
        chown -R builder "$work"
        su builder -c "cd '$work' && makepkg --noconfirm ${MAKEPKG_FLAGS:-}"
    else
        # shellcheck disable=SC2086 # MAKEPKG_FLAGS may hold several flags
        (cd "$work" && makepkg --noconfirm ${MAKEPKG_FLAGS:-})
    fi
    cp "$work"/trace-"${VERSION}"-*.pkg.tar.zst "$DIST/"
    cp packaging/arch/PKGBUILD "$DIST/PKGBUILD"
}

install_deps
case "$KIND" in
    deb) build_deb ;;
    rpm) build_rpm ;;
    arch) build_arch ;;
esac
echo "Built:"
ls -l "$DIST"
